version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-deploy"
s3_bucket = "sam-158383268518"
s3_prefix = "lambda-deploy"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
